apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapp-pod
  name: myapp-pod
spec:
  containers:
  - image: busybox:1.28
    name: myapp-container
    command: ['sh', '-c', 'echo the app is running && sleep 3000']
    env:
    - name: FIRSTNAME
      value: "zphagia"
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo wating for service to be up; sleep 2; done']
